application: case-sensitive-search
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /.*
  script: devchat.py
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
  